# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0032_auto_20170928_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='member',
            field=models.BooleanField(default=False, verbose_name=b'Member'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='source',
            field=models.CharField(default=b'internal', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='membershipopen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='friday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Fridays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='monday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Mondays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Saturdays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Sundays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Thursdays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Tuesdays'),
        ),
        migrations.AlterField(
            model_name='recurringevent',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name=b'Recurs on Wednesdays'),
        ),
    ]
