# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0033_auto_20171002_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='background',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name=b'Background for public pages such as guestlist sign up'),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name=b'Venue logo'),
        ),
    ]
